    Python programlama dilinde veri analizi ve veri işleme işlemleri için kullanılan popüler bir araçtır. Pandas, veri çerçeveleri ve seriler gibi yüksek düzeyli veri yapıları sağlar ve bu veri yapıları üzerinde veri işleme, temizleme ve analiz yapmak için geniş bir işlevsellik sunar. İşte Pandas kütüphanesi hakkında bazı temel bilgiler:
    
    - Numpy'ın özelliklerini kullanır.
    - Yapısal veri setleri ile daha esnek bir şekilde çalışmamızı sağlar. 
    - Numpy'ın aksine **fixed type zorunluluğu yoktur**. Veri seti içerisinde **Kategorik ve Numerik veriler bir arada bulunabilir**.
    - R dilinde kullanılan DataFrame'in Python için hazırlanmış halidir.
    - Değerleri indeksleri ile birlikte tutar.

In [32]:
import numpy as np
import pandas as pd

Pandas Sersi Oluşturma

In [33]:
pd.Series([3, 5, 7, 9, 12])

0     3
1     5
2     7
3     9
4    12
dtype: int64

Yukarıda ilk sütun index , ikinci sütun değerdir .

In [34]:
seri = pd.Series([3, 5, 7, 9, 12])
type(seri)

pandas.core.series.Series

In [35]:
seri.axes

[RangeIndex(start=0, stop=5, step=1)]

.axes veri çerçevesinin satır ve sütun indekslerini döndürür. İndeksler, veri çerçevesindeki satırların ve sütunların etiketlenmesi veya konumlandırılması için kullanılır.

Veri Elaman Sayısı

In [36]:
seri.size

5

Serinin Boyutu

In [37]:
seri.ndim

1

Değerleri Görüntülemek

In [38]:
seri.values

array([ 3,  5,  7,  9, 12], dtype=int64)

In [39]:
seri.head() # İlk beş satırı sunar . 

0     3
1     5
2     7
3     9
4    12
dtype: int64

In [40]:
seri.head(3) # Parentez içine yazılan sayı kadar ilk satırdan veri çekebiliriz .

0    3
1    5
2    7
dtype: int64

In [41]:
seri.tail() # Son beş satırı sunar .

0     3
1     5
2     7
3     9
4    12
dtype: int64

In [42]:
seri.tail(3) # Parentez içine yazılan sayı kadar son satırdan veri çekebiliriz .

2     7
3     9
4    12
dtype: int64

Serinin index İsimlendirmesini kendimiz belirtebiliriz .

In [43]:
data = pd.Series([12, 24, 36, 48, 1], index=['a', 'b', 'c', 'd', 'e'])
data

a    12
b    24
c    36
d    48
e     1
dtype: int64

Aynı Numpy'daki gibi seri içerisindeki verileri aşağıda olduğu gibi çekebiliriz .

In [44]:
data['b']

24

In [45]:
data['a':'c'] # Belirli aralıktaki verileri bu şekilde çekebiliriz .

a    12
b    24
c    36
dtype: int64

Python ' da " Dict " ile Seri Oluşturma 

In [46]:
dict = pd.Series({"reg": 'Ali', "age": 10, "order": 5})
dict

reg      Ali
age       10
order      5
dtype: object

In [47]:
dict["age"]

10

İki Seriyi BİRLEŞTİRME

In [48]:
pd.concat([data, dict])

a         12
b         24
c         36
d         48
e          1
reg      Ali
age       10
order      5
dtype: object

Serilerde Elaman İşlemleri 

In [51]:
a = np.array([1, 2, 3, 4, 5, 6, 7])

In [53]:
data = pd.Series(a, index=['x', 'y', 'v', 'z', 't', 'h', 'f'])

In [54]:
data

x    1
y    2
v    3
z    4
t    5
h    6
f    7
dtype: int32

In [56]:
data[0] # data ' nın ilk elanmanını tanımlançak .

C:\Users\kamal\AppData\Local\Temp\ipykernel_7200\3964897432.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  data[0] # data ' nın ilk elanmanını tanımlançak .


1

In [57]:
data[0:4]

x    1
y    2
v    3
z    4
dtype: int32

Her Bir Değeri Ayrı Ayrı Okumak İstersek 

In [58]:
list(data.items())

[('x', 1), ('y', 2), ('v', 3), ('z', 4), ('t', 5), ('h', 6), ('f', 7)]

Sadece Değerleri Ğeri Getirmek İçin

In [59]:
data.values

array([1, 2, 3, 4, 5, 6, 7])

Elaman Sorğulama 

'x' key ' in içinde mevcut mu ?

In [63]:
'x' in data

True

Fancy

 Pandas veri çerçevesinden veya seriden, belirli koşullara veya belirli bir sıraya dayalı olarak elemanlara erişmeyi ifade eder. 

In [64]:
data[['x', 'y']]

x    1
y    2
dtype: int32

In [65]:
data['x':'t']

x    1
y    2
v    3
z    4
t    5
dtype: int32

Value Üzerinden Yeni Değer Atama 

In [67]:
 data['x']

1

In [70]:
data['x'] = 100
data

x    100
y      2
v      3
z      4
t      5
h      6
f      7
dtype: int32

DataFrame Oluşturma

In [71]:
list = [1, 5, 7, 9]

In [72]:
pd.DataFrame(list, columns=["kolon_adi"])

kolon_adi
0          1
1          5
2          7
3          9

Numpy ile DataFrame Oluşturup Bunu Pandas DataFrame Çevirme 

In [77]:
m = np.arange(1,10)
m

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [78]:
m = np.arange(1,10).reshape(3, 3)
m

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [80]:
df = pd.DataFrame(m, columns=['column_1', 'column_2', 'column_3'])
df

column_1  column_2  column_3
0         1         2         3
1         4         5         6
2         7         8         9

In [82]:
type(df) # Verini türünü gözden ğeçirelim .

pandas.core.frame.DataFrame

In [84]:
df.shape # df boyutuna .shape ile bakabiliriz .

(3, 3)

In [86]:
df.ndim # Bir veri çerçevesinin veya serinin kaç boyutlu olduğunu gösterir.

2

 LOC & ILOC (Gözlem ve Değişken Seçimi) 

**LOC**: Tanımlandığı şekli ile seçim yapmak için kullanılır. Yani 0'dan 3'e kadar değil, 3 dahil satırları getirir.

**ILOC:** Alışık olduğumuz indeksleme mantığı ile seçim yapar. Yani 0'dan 3'e kadar olan (3 hariç) satırları getirir. 

In [107]:
n = np.random.randint(1, 30, size=(10,3))
df = pd.DataFrame(n, columns=['var1', 'var2', 'var3'])

df

var1  var2  var3
0    23    26    18
1    15    14    24
2     6    18     1
3     6    23    23
4    10     6    11
5    26    26    22
6     7     4    20
7    10     1    17
8    22    17    17
9     4    13    18

In [108]:
df.loc[0:3]

var1  var2  var3
0    23    26    18
1    15    14    24
2     6    18     1
3     6    23    23

In [109]:
df.iloc[0:3]

var1  var2  var3
0    23    26    18
1    15    14    24
2     6    18     1

Bir Elaman Seçmek İstersek ! . .

In [112]:
df.iloc[0, 0]

23

In [114]:
df.iloc[:5, :2]

var1  var2
0    23    26
1    15    14
2     6    18
3     6    23
4    10     6

In [117]:
df.iloc[2:7]['var3']

2     1
3    23
4    11
5    22
6    20
Name: var3, dtype: int32

Iloc ile Loc hakkında aklınızda tutmanız gereken fark, **loc** ile spesifik değişken belirterek gözlem çekebiliyorken **iloc** ile bunu eskiden öğrendiğimiz yöntemle (yukarıdaki son 2 örnekteki gibi) yapabiliyoruz.

**Koşullu Elaman İşlemleri**

In [118]:
df # Önçelikle verimizi çekelim .

var1  var2  var3
0    23    26    18
1    15    14    24
2     6    18     1
3     6    23    23
4    10     6    11
5    26    26    22
6     7     4    20
7    10     1    17
8    22    17    17
9     4    13    18

In [119]:
df[df.var1 < 15] # Verilerimiz içinde 15'den küçük olanları çekelim . 

var1  var2  var3
2     6    18     1
3     6    23    23
4    10     6    11
6     7     4    20
7    10     1    17
9     4    13    18

In [120]:
df[df.var1 > 15] # Verilerimiz içinde 15'den büyük olanları çekelim . 

var1  var2  var3
0    23    26    18
5    26    26    22
8    22    17    17

In [123]:
df[df.var1 < 15][["var1"]] # var1 verimiz içinde 15'den küçük olanları çekelim . 

var1
2     6
3     6
4    10
6     7
7    10
9     4

Birden Fazla Koşul Girmek İstersek

Seçeceğimiz gözlemler(satırlar) 15'ten küçük, 5'ten büyük olsun (var1 için)Seçeceğimiz gözlemler(satırlar) 15'ten küçük, 5'ten büyük olsun (var1 için)

In [125]:
df[(df.var1 < 15) & (df.var2 > 5)][["var1"]]

var1
2     6
3     6
4    10
9     4

In [127]:
df[(df.var1 < 15) & (df.var2 > 5)][["var1", "var2"]]

var1  var2
2     6    18
3     6    23
4    10     6
9     4    13

Join Birleştirme İşlemleri

In [128]:
df

var1  var2  var3
0    23    26    18
1    15    14    24
2     6    18     1
3     6    23    23
4    10     6    11
5    26    26    22
6     7     4    20
7    10     1    17
8    22    17    17
9     4    13    18

In [130]:
df1 = df + 99   # Her veriyi +99 ile toplayalım .
df1

var1  var2  var3
0   122   125   117
1   114   113   123
2   105   117   100
3   105   122   122
4   109   105   110
5   125   125   121
6   106   103   119
7   109   100   116
8   121   116   116
9   103   112   117

In [131]:
pd.concat([df, df1])

var1  var2  var3
0    23    26    18
1    15    14    24
2     6    18     1
3     6    23    23
4    10     6    11
5    26    26    22
6     7     4    20
7    10     1    17
8    22    17    17
9     4    13    18
0   122   125   117
1   114   113   123
2   105   117   100
3   105   122   122
4   109   105   110
5   125   125   121
6   106   103   119
7   109   100   116
8   121   116   116
9   103   112   117